version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge