version: '3.9'

services:
  node-app:
    image: node:18
    container_name: node_app_container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
